apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pyramidRoutingApp.fullname" . }}-ingress
  annotations:
    kubernetes.io/tls-acme: 'true'
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/app-root: {{ .Values.ingress.rootPath}}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.ingress.hostName }}
    secretName: letsencrypt-tls
  rules:
  - host: {{ .Values.ingress.hostName }}
    http:
      paths:
      - path: /routes
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-routes-app
            port:
              number: 80
      - path: /weather
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-weather-app
            port:
              number: 80
      - path: /geography
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-geography-app
            port:
              number: 80
      - path: /environment-infrastructure
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-environment-infrastructure-app
            port:
              number: 80