apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mosquittoMqtt.fullname" . }}-conf
  labels:
    app: {{ include "mosquittoMqtt.fullname" . }}
data:
  mosquitto.conf: | 
    listener 1883
    allow_anonymous true
    max_queued_messages 50000
