apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquittoMqtt.fullname" . }}
  labels:
    {{- include "mosquittoMqtt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 1883
      protocol: TCP
      name: mqtt
  selector:
    {{- include "mosquittoMqtt.selectorLabels" . | nindent 4 }}
