//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.10 at 09:50:27 AM BST 
//


package aero.aixm.schema._5;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import net.opengis.gml._3.AbstractGMLType;


/**
 * Base type for AIXM complex types that are NOT features. For example, City, ContactInformation, AirspaceVolume, etc. It derives from AbstractGMLType so that AIXM objects are recognised as GML objects, thus ensuring that GML-aware applications recognise them properly. Retains only the mandatory gml:id attribute.
 * 
 * <p>Java class for AbstractAIXMObjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractAIXMObjectType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.opengis.net/gml/3.2}AbstractGMLType">
 *       &lt;sequence>
 *         &lt;sequence>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://www.opengis.net/gml/3.2}id use="required""/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractAIXMObjectType")
@XmlSeeAlso({
    AbstractExtensionType.class,
    NavaidComponentType.class,
    AirspaceGeometryComponentType.class,
    RoutePortionType.class,
    AirspaceVolumeType.class,
    SurfaceCharacteristicsType.class,
    MarkingElementType.class,
    StandardLevelType.class,
    RidgeType.class,
    FlightConditionCircumstanceType.class,
    AbstractDirectFlightType.class,
    CallsignDetailType.class,
    LightActivationType.class,
    MinimaType.class,
    OilType.class,
    ProcedureTransitionType.class,
    ProcedureTransitionLegType.class,
    EquipmentUnavailableAdjustmentType.class,
    ApproachTimingTableType.class,
    LandingTakeoffAreaCollectionType.class,
    DepartureArrivalConditionType.class,
    HoldingPatternDistanceType.class,
    LinguisticNoteType.class,
    PointReferenceType.class,
    ReflectorType.class,
    SurfaceContaminationLayerType.class,
    FlightRestrictionRouteType.class,
    AngleUseType.class,
    FlightRoutingElementType.class,
    FuelType.class,
    FlightRestrictionLevelType.class,
    OxygenType.class,
    SectorDesignType.class,
    NitrogenType.class,
    RadarComponentType.class,
    EquipmentUnavailableAdjustmentColumnType.class,
    ObstructionType.class,
    ApproachDistanceTableType.class,
    AuthorityForSpecialNavigationStationType.class,
    HoldingPatternDurationType.class,
    AerialRefuellingAnchorType.class,
    TimesheetType.class,
    AbstractSurfaceContaminationType.class,
    UnitDependencyType.class,
    ApproachConditionType.class,
    AirspaceLayerType.class,
    AerialRefuellingTrackType.class,
    NoteType.class,
    ApproachAltitudeTableType.class,
    CircleSectorType.class,
    AirspaceVolumeDependencyType.class,
    AuthorityForAerialRefuellingType.class,
    LightElementType.class,
    FASDataBlockType.class,
    AircraftCharacteristicType.class,
    HoldingUseType.class,
    MissedApproachGroupType.class,
    ObstacleAssessmentAreaType.class,
    OrganisationAuthorityAssociationType.class,
    MeteorologyType.class,
    AbstractPropertiesWithScheduleType.class,
    AltitudeAdjustmentType.class,
    CityType.class,
    RunwayDeclaredDistanceType.class,
    SurveillanceGroundStationType.class,
    FlightConditionElementType.class,
    ContactInformationType.class,
    TerminalArrivalAreaSectorType.class,
    ObstaclePlacementType.class,
    FinalProfileType.class,
    AbstractSegmentPointType.class,
    FlightCharacteristicType.class,
    AuthorityForSpecialNavigationSystemType.class,
    AuthorityForNavaidEquipmentType.class,
    SafeAltitudeAreaSectorType.class,
    AbstractUsageConditionType.class,
    NavaidEquipmentDistanceType.class,
    NavigationAreaSectorType.class
})
public abstract class AbstractAIXMObjectType
    extends AbstractGMLType
{


}
