//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.10 at 09:50:27 AM BST 
//


package aero.aixm.schema._5;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * It provides a basis for deriving AIXM feature/object properties. It defines the nilReason attribute and currently, it is only used for properties that are derived from association with an AIM object.
 * 
 * <p>Java class for AbstractAIXMPropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractAIXMPropertyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="nilReason" type="{http://www.opengis.net/gml/3.2}NilReasonEnumeration" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractAIXMPropertyType")
@XmlSeeAlso({
    OnlineContactPropertyType.class,
    SafeAltitudeAreaSectorPropertyType.class,
    NitrogenPropertyType.class,
    AirportHeliportAvailabilityPropertyType.class,
    ObstaclePlacementPropertyType.class,
    ElevatedSurfacePropertyType.class,
    PropertiesWithSchedulePropertyType.class,
    RadarComponentPropertyType.class,
    FlightConditionCombinationPropertyType.class,
    AuthorityForAerialRefuellingPropertyType.class,
    FlightRoutingElementPropertyType.class,
    PointPropertyType.class,
    ElevatedPointPropertyType.class,
    LandingTakeoffAreaCollectionPropertyType.class,
    TimesheetPropertyType.class,
    FlightRestrictionRoutePropertyType.class,
    AerialRefuellingTrackPropertyType.class,
    TaxiwayContaminationPropertyType.class,
    SectorDesignPropertyType.class,
    WorkareaActivityPropertyType.class,
    ConditionCombinationPropertyType.class,
    UnitAvailabilityPropertyType.class,
    PostalAddressPropertyType.class,
    AuthorityForSpecialNavigationSystemPropertyType.class,
    AuthorityForNavaidEquipmentPropertyType.class,
    AngleUsePropertyType.class,
    OrganisationAuthorityAssociationPropertyType.class,
    SurveillanceGroundStationPropertyType.class,
    LightActivationPropertyType.class,
    AircraftStandContaminationPropertyType.class,
    ApronAreaAvailabilityPropertyType.class,
    GroundLightingAvailabilityPropertyType.class,
    DirectFlightClassPropertyType.class,
    RunwaySectionContaminationPropertyType.class,
    OilPropertyType.class,
    AirspaceActivationPropertyType.class,
    ContactInformationPropertyType.class,
    ReflectorPropertyType.class,
    CallsignDetailPropertyType.class,
    NavaidComponentPropertyType.class,
    FlightCharacteristicPropertyType.class,
    ObstructionPropertyType.class,
    DirectFlightSegmentPropertyType.class,
    NavaidOperationalStatusPropertyType.class,
    AirportHeliportResponsibilityOrganisationPropertyType.class,
    SegmentPointPropertyType.class,
    PointReferencePropertyType.class,
    SurfaceContaminationPropertyType.class,
    TerminalSegmentPointPropertyType.class,
    ApproachAltitudeTablePropertyType.class,
    HoldingUsePropertyType.class,
    RidgePropertyType.class,
    AltimeterSourceStatusPropertyType.class,
    FASDataBlockPropertyType.class,
    ManoeuvringAreaAvailabilityPropertyType.class,
    LinguisticNotePropertyType.class,
    ApronAreaUsagePropertyType.class,
    SurfacePropertyType.class,
    LightElementPropertyType.class,
    AirportHeliportContaminationPropertyType.class,
    RadioCommunicationOperationalStatusPropertyType.class,
    EquipmentUnavailableAdjustmentColumnPropertyType.class,
    VerticalStructureLightingStatusPropertyType.class,
    NavaidEquipmentMonitoringPropertyType.class,
    NotePropertyType.class,
    ApproachConditionPropertyType.class,
    AerialRefuellingAnchorPropertyType.class,
    AirspaceGeometryComponentPropertyType.class,
    RoutePortionPropertyType.class,
    NavaidEquipmentDistancePropertyType.class,
    MinimaPropertyType.class,
    RouteAvailabilityPropertyType.class,
    CircleSectorPropertyType.class,
    UsageConditionPropertyType.class,
    FinalProfilePropertyType.class,
    AirspaceLayerClassPropertyType.class,
    AirportHeliportUsagePropertyType.class,
    FlightConditionCircumstancePropertyType.class,
    ServiceOperationalStatusPropertyType.class,
    ProcedureTransitionLegPropertyType.class,
    AirspaceVolumePropertyType.class,
    DepartureArrivalConditionPropertyType.class,
    FuelPropertyType.class,
    CirclingRestrictionPropertyType.class,
    RunwayDeclaredDistancePropertyType.class,
    RunwayContaminationPropertyType.class,
    ProcedureTransitionPropertyType.class,
    AuthorityForSpecialNavigationStationPropertyType.class,
    ManoeuvringAreaUsagePropertyType.class,
    VerticalStructurePartPropertyType.class,
    MeteorologyPropertyType.class,
    TerminalArrivalAreaSectorPropertyType.class,
    FlightRestrictionLevelPropertyType.class,
    OxygenPropertyType.class,
    LightElementStatusPropertyType.class,
    TouchDownLiftOffContaminationPropertyType.class,
    AltitudeAdjustmentPropertyType.class,
    EquipmentUnavailableAdjustmentPropertyType.class,
    ObstacleAssessmentAreaPropertyType.class,
    ApproachTimingTablePropertyType.class,
    AircraftCharacteristicPropertyType.class,
    RunwayDeclaredDistanceValuePropertyType.class,
    TelephoneContactPropertyType.class,
    ApproachDistanceTablePropertyType.class,
    SpecialNavigationStationStatusPropertyType.class,
    UnitDependencyPropertyType.class,
    ProcedureAvailabilityPropertyType.class,
    HoldingPatternDurationPropertyType.class,
    FlightConditionElementPropertyType.class,
    AirspaceLayerPropertyType.class,
    StandardLevelPropertyType.class,
    MissedApproachGroupPropertyType.class,
    SurfaceContaminationLayerPropertyType.class,
    CityPropertyType.class,
    AerialRefuellingPointPropertyType.class,
    HoldingPatternDistancePropertyType.class,
    MarkingElementPropertyType.class,
    SurfaceCharacteristicsPropertyType.class,
    EnRouteSegmentPointPropertyType.class,
    ElevatedCurvePropertyType.class,
    NavigationAreaSectorPropertyType.class,
    DirectFlightPropertyType.class,
    CurvePropertyType.class,
    AirspaceVolumeDependencyPropertyType.class,
    ApronContaminationPropertyType.class
})
public abstract class AbstractAIXMPropertyType {

    @XmlAttribute(name = "nilReason")
    protected String nilReason;

    /**
     * Gets the value of the nilReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNilReason() {
        return nilReason;
    }

    /**
     * Sets the value of the nilReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNilReason(String value) {
        this.nilReason = value;
    }

}
