//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.10 at 09:50:27 AM BST 
//


package aero.aixm.schema._5;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SegmentPointPropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SegmentPointPropertyType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.aixm.aero/schema/5.1}AbstractAIXMPropertyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.aixm.aero/schema/5.1}AbstractSegmentPoint"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SegmentPointPropertyType", propOrder = {
    "abstractSegmentPoint"
})
public class SegmentPointPropertyType
    extends AbstractAIXMPropertyType
{

    @XmlElementRef(name = "AbstractSegmentPoint", namespace = "http://www.aixm.aero/schema/5.1", type = JAXBElement.class)
    protected JAXBElement<? extends AbstractSegmentPointType> abstractSegmentPoint;

    /**
     * Gets the value of the abstractSegmentPoint property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AerialRefuellingPointType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractSegmentPointType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TerminalSegmentPointType }{@code >}
     *     {@link JAXBElement }{@code <}{@link EnRouteSegmentPointType }{@code >}
     *     
     */
    public JAXBElement<? extends AbstractSegmentPointType> getAbstractSegmentPoint() {
        return abstractSegmentPoint;
    }

    /**
     * Sets the value of the abstractSegmentPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AerialRefuellingPointType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractSegmentPointType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TerminalSegmentPointType }{@code >}
     *     {@link JAXBElement }{@code <}{@link EnRouteSegmentPointType }{@code >}
     *     
     */
    public void setAbstractSegmentPoint(JAXBElement<? extends AbstractSegmentPointType> value) {
        this.abstractSegmentPoint = value;
    }

}
