//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.10 at 09:50:27 AM BST 
//


package net.opengis.gml._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/gml/3.2}SecondDefiningParameter_GL"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "secondDefiningParameterGL"
})
@XmlRootElement(name = "secondDefiningParameter")
public class SecondDefiningParameter {

    @XmlElement(name = "SecondDefiningParameter_GL", required = true)
    protected SecondDefiningParameterGL secondDefiningParameterGL;

    /**
     * Gets the value of the secondDefiningParameterGL property.
     * 
     * @return
     *     possible object is
     *     {@link SecondDefiningParameterGL }
     *     
     */
    public SecondDefiningParameterGL getSecondDefiningParameterGL() {
        return secondDefiningParameterGL;
    }

    /**
     * Sets the value of the secondDefiningParameterGL property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecondDefiningParameterGL }
     *     
     */
    public void setSecondDefiningParameterGL(SecondDefiningParameterGL value) {
        this.secondDefiningParameterGL = value;
    }

}
