apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "routesApp.fullname" . }}
  labels:
    {{- include "routesApp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "routesApp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "routesApp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "routesApp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POST_ROUTE_SERVICE
              value: http://{{ .Release.Name }}-routes-required-services-app:80/routes-required-services/route
            - name: CALCULATE_LEG_SERVICE
              value: http://{{ .Release.Name }}-routes-calculation-extension-app:80/routes-calculation-extension/calculate-leg
            - name: SPATIAL_CONSTRAINTS_SERVICE
              value: http://{{ .Release.Name }}-routes-required-services-app:80/routes-required-services/spatial-constraints
            - name: VEHICLE_PERFORMANCE_SERVICE
              value: http://{{ .Release.Name }}-routes-required-services-app:80/routes-required-services/vehicle-performance
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
