apiVersion: v1
kind: Service
metadata:
  name: {{ include "environmentInfrastructureApp.fullname" . }}
  labels:
    {{- include "environmentInfrastructureApp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "environmentInfrastructureApp.selectorLabels" . | nindent 4 }}
