//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.10 at 12:04:33 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.aixm.aero/schema/5.1/message", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package aero.aixm.schema._5_1.message;
