apiVersion: v1
kind: Service
metadata:
  name: {{ include "environmentInfrastructureDb.fullname" . }}
  labels:
    {{- include "environmentInfrastructureDb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: sql
      protocol: TCP
      name: sql
  selector:
    {{- include "environmentInfrastructureDb.selectorLabels" . | nindent 4 }}
