//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.10 at 09:50:27 AM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.isotc211.org/2005/gts", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.isotc211._2005.gts;
